name: Jest coverage
on: pull_request

jobs:
  test:
    permissions:
      checks: write
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    if: (!startsWith(github.head_ref, 'renovate'))
    steps:
      - uses: actions/checkout@v4
      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NVMRC }}
      - uses: pnpm/action-setup@v4.0.0
        name: install pnpm
        id: pnpm-install
        with:
          version: 9.11.0
          run_install: false
      - name: access pnpm cache
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4.0.2
        name: update pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm install
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: install
          package-manager: pnpm
          annotations: none
